selenium:
    base_url: "https://www.interpol.int/How-we-work/Notices/Red-Notices/View-Red-Notices#"
search:
    search_method:
        list_item: "css selector"
    search_value:
        list_item: ".redNoticesList__item.notice_red"


http:
    base_url: "https://ws-public.interpol.int/notices/v1/red?resultPerPage="
    number_of_results: "20"

